on:
  workflow_dispatch:

jobs:
  hybrid_job:
    runs-on: ubuntu-latest
    steps:
      - name: run a cmd in ubuntu
        run: echo "Hello from ubuntu"
      - name: run inside a alpine container 
        uses: docker://alpine:3.18
        with:
          entrypoint: /bin/sh
          args: -c 'echo "Hello from alpine container"'

      - name: run a cmd in ubuntu 
        run: echo "Hello from ubuntu"