  name: frist_workflow
  
  on:
    push: 
      branches:
        - main
  jobs:
    exanple_job:
      runs-on: ubunto-latest


      steps:
        - name: print a welcome massage
          run: echo "welcome "

      - name: checkout repo 
        uses: action/checkout@v4.2.2


      - name: list repo files 
        run: ls -la 
